### ISSUE TITLE
Call to client.loop() requirement of PubSubClient library

### ISSUE THREAD

**Issue by elguiri** [ycardon/d1mini-sht30-mqtt#2]
Useful idea of putting the device to sleep, thanks. Later versions of PubSubClient require a call to client.loop() before the deep sleep command; see here https://github.com/knolleary/pubsubclient/issues/634#issuecomment-673527444

**Comment by ycardon** [comment]
Thank you for the update! 

Would you mind to submit a pull request for this ? (I cannot test the changes as I don't use anymore this code: I've moved my sensors to the [ESP Home](https://esphome.io/) ecosystem).

If not, I will leave this issue open for future readers.

**Comment by ycardon** [comment]
For the records, this is the declaration file I have in ESP Home for an equivalent functionality:
```yaml
esphome:
  name: d1mini_cave
  platform: ESP8266
  board: d1_mini
  board_flash_mode: dout

## --- CONNECTIVITY ---

wifi:
  networks:
    - bssid: xx:xx:xx:xx:xx:x
      password: xxxxxxxxxxxxxxxxxxxx

mqtt:
  broker: 192.168.xx.xx
  username: xxxxxx
  password: xxxxxxxxxxx

  # prevents from appearing offline during deep sleep
  birth_message:
    topic: d1mini_cave/status
    payload: online
  will_message:
    topic: d1mini_cave/status
    payload: online

## --- FEATURES ---

deep_sleep:
  run_duration: 20s
  sleep_duration: 580s
  id: deep_sleep_1

## --- SENSORS ---

i2c:

sensor:
  - platform: sht3xd
    address: 0x45
    temperature:
      name: "Cave temperature"
    humidity:
      name: "Cave humidity"
    update_interval: 15s
```
